# For examples and documentation, start at:
# http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-example
# Based on:
# https://github.com/JasonSwindle/codebuild-ecr-test/blob/master/buildspec.yml

version: 0.1

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo "Build started on `date -u +%FT%TZ` (ISO-8601)"
      - echo "Building the Docker image"
      - docker build -t $IMAGE_REPO_NAME:$(printenv CODEBUILD_BUILD_ID | awk -F':' '{print $2}') .
      - docker tag $IMAGE_REPO_NAME:$(printenv CODEBUILD_BUILD_ID | awk -F':' '{print $2}') $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$(printenv CODEBUILD_BUILD_ID | awk -F':' '{print $2}')
  post_build:
    commands:
      - echo "Build completed on `date -u +%FT%TZ` (ISO-8601)"
      - echo "Pushing the Docker image"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$(printenv CODEBUILD_BUILD_ID | awk -F':' '{print $2}')
